name: 🏷️ Sync README to Docker Hub

on:
  push:
    branches: [ "main" ]
    paths:
      - "README.md"
      - ".github/workflows/update-dockerhub.yml"

jobs:
  update-description:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update Docker Hub description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          repository: ${{ secrets.DOCKER_USERNAME }}/internet-monitor
          readme-filepath: ./README.md
